version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: finlab_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: 'mongod --auth'

  minio:
    image: minio/minio
    container_name: finlab_minio
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
